// 小米设备内置 APK 推荐精简清单数据
// 数据来源于仓库精简命令文件中的推荐精简项（已验证可精简）
// 路径: apk-data.js  v1.14.0
// 结构：APP_DATA[设备类型] = [{ cat: 类别, items: [{ pkg, desc, risk }] }]
// risk 取值：safe(可安全精简) / caution(精简后可能影响功能,谨慎) / danger(核心组件,严禁精简)
// 设备类型：phone(手机) / pad(平板,复用手机) / tv(电视盒)

const APP_DATA = {
  phone: [
    { cat: "系统核心（严禁精简）", items: [
      { pkg: "com.android.settings", desc: "系统设置", risk: "danger" },
      { pkg: "com.miui.home", desc: "系统桌面 Launcher", risk: "danger" },
      { pkg: "com.android.systemui", desc: "系统界面", risk: "danger" },
      { pkg: "android", desc: "Android 框架核心", risk: "danger" },
    ]},
    { cat: "广告模块", items: [
      { pkg: "com.android.adservices.api", desc: "广告服务", risk: "safe" },
      { pkg: "com.miui.analytics", desc: "小米统计", risk: "safe" },
      { pkg: "com.miui.systemAdSolution", desc: "系统广告", risk: "safe" },
      { pkg: "com.xiaomi.ab", desc: "AB 实验", risk: "safe" },
      { pkg: "com.miui.daemon", desc: "后台守护", risk: "safe" },
    ]},
    { cat: "输入法", items: [
      { pkg: "com.baidu.duersdk.opensdk", desc: "百度语音 SDK", risk: "caution" },
      { pkg: "com.baidu.input_mi", desc: "百度输入法", risk: "caution" },
      { pkg: "com.iflytek.inputmethod.miui", desc: "讯飞输入法", risk: "caution" },
      { pkg: "com.sohu.inputmethod.sogou.xiaomi", desc: "搜狗输入法", risk: "caution" },
    ]},
    { cat: "安卓系统自带", items: [
      { pkg: "com.android.dreams.basic", desc: "屏保基础", risk: "safe" },
      { pkg: "com.android.dreams.phototable", desc: "相册屏保", risk: "safe" },
      { pkg: "com.android.htmlviewer", desc: "HTML 查看器", risk: "safe" },
      { pkg: "com.android.location.fused", desc: "融合定位", risk: "caution" },
      { pkg: "com.android.musicfx", desc: "音效增强", risk: "safe" },
      { pkg: "com.android.wallpaper.livepicker", desc: "动态壁纸选择器", risk: "safe" },
      { pkg: "com.android.wallpaperbackup", desc: "壁纸备份", risk: "safe" },
      { pkg: "com.bsp.catchlog", desc: "日志捕获", risk: "safe" },
    ]},
    { cat: "音效", items: [
      { pkg: "com.atmos", desc: "杜比全景声", risk: "caution" },
      { pkg: "com.miui.audioeffect", desc: "小米音效", risk: "caution" },
      { pkg: "com.atmos.daxappUI", desc: "杜比界面", risk: "caution" },
    ]},
    { cat: "系统配色主题", items: [
      { pkg: "com.android.theme.color.cinnamon", desc: "主题色-肉桂", risk: "safe" },
      { pkg: "com.android.theme.color.green", desc: "主题色-绿", risk: "safe" },
      { pkg: "com.android.theme.color.ocean", desc: "主题色-海洋", risk: "safe" },
      { pkg: "com.android.theme.color.orchid", desc: "主题色-兰", risk: "safe" },
      { pkg: "com.android.theme.color.purple", desc: "主题色-紫", risk: "safe" },
    ]},
    { cat: "超级壁纸", items: [
      { pkg: "com.miui.miwallpaper.earth", desc: "超级壁纸-地球", risk: "safe" },
      { pkg: "com.miui.miwallpaper.geometry", desc: "超级壁纸-几何", risk: "safe" },
      { pkg: "com.miui.miwallpaper.mars", desc: "超级壁纸-火星", risk: "safe" },
      { pkg: "com.miui.miwallpaper.saturn", desc: "超级壁纸-土星", risk: "safe" },
      { pkg: "com.miui.miwallpaper.snowmountain", desc: "超级壁纸-雪山", risk: "safe" },
    ]},
    { cat: "小米自带应用", items: [
      { pkg: "com.duokan.reader", desc: "多看阅读", risk: "safe" },
      { pkg: "com.duokan.videodaily", desc: "多看视频", risk: "safe" },
      { pkg: "com.mfashiongallery.emag", desc: "时尚画报", risk: "safe" },
      { pkg: "com.mi.dlabs.vr", desc: "小米 VR", risk: "safe" },
      { pkg: "com.miui.aod", desc: "息屏显示", risk: "caution" },
      { pkg: "com.miui.audiomonitor", desc: "音频监控", risk: "safe" },
      { pkg: "com.miui.bugreport", desc: "错误报告", risk: "safe" },
      { pkg: "com.miui.hybrid.accessory", desc: "混合应用组件", risk: "safe" },
      { pkg: "com.xiaomi.mtb", desc: "小米测试工具", risk: "safe" },
      { pkg: "com.miui.newhome", desc: "新版桌面", risk: "caution" },
      { pkg: "com.miui.sysopt", desc: "系统优化", risk: "safe" },
      { pkg: "com.miui.thirdappassistant", desc: "第三方助手", risk: "safe" },
      { pkg: "com.miui.touchassistant", desc: "触摸助手", risk: "safe" },
      { pkg: "com.miui.translation.kingsoft", desc: "金山翻译", risk: "safe" },
      { pkg: "com.miui.translation.youdao", desc: "有道翻译", risk: "safe" },
      { pkg: "com.miui.userguide", desc: "用户指南", risk: "safe" },
      { pkg: "com.miui.whetstone", desc: "进程管理", risk: "safe" },
      { pkg: "com.miui.wmsvc", desc: "窗口管理服务", risk: "caution" },
      { pkg: "com.xiaomi.gamecenter", desc: "小米游戏中心", risk: "safe" },
      { pkg: "com.xiaomi.gamecenter.sdk.service", desc: "游戏 SDK 服务", risk: "safe" },
      { pkg: "com.xiaomi.joyose", desc: "Joyose 调度", risk: "caution" },
      { pkg: "com.xiaomi.mi_connect_service", desc: "妙享连接", risk: "caution" },
      { pkg: "com.xiaomi.migameservice", desc: "小米游戏服务", risk: "safe" },
      { pkg: "com.xiaomi.macro", desc: "自动连招", risk: "safe" },
      { pkg: "com.xiaomi.payment", desc: "小米支付", risk: "caution" },
    ]},
    { cat: "手机测试", items: [
      { pkg: "com.huaqin.factory", desc: "华勤工厂测试", risk: "safe" },
      { pkg: "com.longcheertel.AutoTest", desc: "龙旗自动测试", risk: "safe" },
      { pkg: "com.longcheertel.cit", desc: "龙旗 CIT", risk: "safe" },
      { pkg: "com.longcheertel.midtest", desc: "龙旗中间测试", risk: "safe" },
      { pkg: "com.longcheertel.modemlog", desc: "龙旗基带日志", risk: "safe" },
      { pkg: "com.longcheertel.smsregister", desc: "龙旗短信注册", risk: "safe" },
      { pkg: "com.mi.AutoTest", desc: "小米自动测试", risk: "safe" },
      { pkg: "com.modemdebug", desc: "基带调试", risk: "safe" },
    ]},
    { cat: "MTK 平台", items: [
      { pkg: "com.mediatek.floatmenu", desc: "MTK 悬浮菜单", risk: "safe" },
      { pkg: "com.mediatek.mdmlsample", desc: "MTK MDML 示例", risk: "safe" },
      { pkg: "com.mediatek.mtklogger", desc: "MTK 日志", risk: "safe" },
      { pkg: "com.mediatek.providers.drm", desc: "MTK DRM", risk: "safe" },
    ]},
    { cat: "HyperOS 系统应用", items: [
      { pkg: "com.miui.cleanmaster", desc: "安全中心清理", risk: "safe" },
      { pkg: "com.miui.securitycenter", desc: "手机管家/安全中心", risk: "caution" },
      { pkg: "com.miui.securitycore", desc: "安全核心组件", risk: "caution" },
      { pkg: "com.miui.securityadd", desc: "安全附加组件", risk: "caution" },
      { pkg: "com.miui.personalassistant", desc: "小爱建议/个人助理", risk: "safe" },
      { pkg: "com.miui.mediaeditor", desc: "相册编辑", risk: "safe" },
      { pkg: "com.miui.notes", desc: "笔记", risk: "safe" },
      { pkg: "com.miui.screenrecorder", desc: "屏幕录制", risk: "safe" },
      { pkg: "com.miui.screenshot", desc: "截屏", risk: "safe" },
      { pkg: "com.miui.weather2", desc: "天气", risk: "safe" },
      { pkg: "com.miui.calculator", desc: "计算器", risk: "safe" },
      { pkg: "com.miui.compass", desc: "指南针", risk: "safe" },
      { pkg: "com.miui.gallery", desc: "相册", risk: "caution" },
      { pkg: "com.miui.player", desc: "小米音乐", risk: "safe" },
      { pkg: "com.miui.hybrid", desc: "混合应用容器", risk: "safe" },
      { pkg: "com.miui.contentextension", desc: "内容扩展", risk: "safe" },
      { pkg: "com.miui.contentcatcher", desc: "内容捕获", risk: "safe" },
      { pkg: "com.miui.notification", desc: "通知助手", risk: "safe" },
      { pkg: "com.miui.phrase", desc: "短语快捷输入", risk: "safe" },
      { pkg: "com.miui.voiceassist", desc: "小爱语音助手", risk: "caution" },
      { pkg: "com.miui.carlink", desc: "妙享中心·车机互联", risk: "safe" },
      { pkg: "com.miui.mishare.connectivity", desc: "小米互传", risk: "caution" },
      { pkg: "com.miui.findmy", desc: "查找设备", risk: "caution" },
      { pkg: "com.miui.greenguard", desc: "儿童模式/绿盾", risk: "safe" },
      { pkg: "com.miui.guardprovider", desc: "安全提供组件", risk: "caution" },
      { pkg: "com.miui.backup", desc: "本地备份", risk: "safe" },
      { pkg: "com.miui.cloudbackup", desc: "云备份", risk: "safe" },
      { pkg: "com.miui.cloudservice", desc: "云服务", risk: "caution" },
      { pkg: "com.miui.micloudsync", desc: "云同步", risk: "caution" },
      { pkg: "com.miui.newmidrive", desc: "小米云盘", risk: "safe" },
      { pkg: "com.miui.rom", desc: "ROM 服务", risk: "safe" },
      { pkg: "com.miui.tsmclient", desc: "小米钱包/NFC 卡", risk: "caution" },
      { pkg: "com.miui.virtualsim", desc: "虚拟 SIM 卡", risk: "safe" },
    ]},
    { cat: "HyperOS 小米服务", items: [
      { pkg: "com.xiaomi.account", desc: "小米账号", risk: "caution" },
      { pkg: "com.xiaomi.market", desc: "应用商店", risk: "safe" },
      { pkg: "com.xiaomi.shop", desc: "小米商城", risk: "safe" },
      { pkg: "com.xiaomi.mirror", desc: "小米投屏/镜像", risk: "caution" },
      { pkg: "com.xiaomi.scanner", desc: "扫描", risk: "safe" },
      { pkg: "com.xiaomi.misettings", desc: "小米设置(扩展)", risk: "caution" },
      { pkg: "com.xiaomi.simactivate.service", desc: "SIM 卡激活服务", risk: "safe" },
      { pkg: "com.xiaomi.otrpbroker", desc: "OTA 代理", risk: "safe" },
      { pkg: "com.xiaomi.security.onetrack", desc: "小米统计上报", risk: "safe" },
      { pkg: "com.xiaomi.finddevice", desc: "查找设备", risk: "caution" },
      { pkg: "com.xiaomi.trustservice", desc: "信任服务", risk: "caution" },
      { pkg: "com.xiaomi.hypercomm", desc: "澎湃通信增强", risk: "caution" },
      { pkg: "com.xiaomi.metoknlp", desc: "网络定位服务", risk: "safe" },
      { pkg: "com.xiaomi.gnss.polaris", desc: "GNSS 定位", risk: "safe" },
      { pkg: "com.xiaomi.continuity.sdkapp", desc: "妙享互联", risk: "caution" },
      { pkg: "com.xiaomi.cameratools", desc: "相机工具", risk: "safe" },
      { pkg: "com.xiaomi.cameramind", desc: "相机智能场景", risk: "safe" },
      { pkg: "com.xiaomi.barrage", desc: "弹幕/评论组件", risk: "safe" },
      { pkg: "com.xiaomi.aon", desc: "AON 低功耗显示", risk: "safe" },
      { pkg: "com.xiaomi.aiasst.service", desc: "小爱助手服务", risk: "caution" },
      { pkg: "com.xiaomi.aicr", desc: "AI 通话摘要", risk: "safe" },
      { pkg: "com.xiaomi.digitalkey", desc: "数字车钥匙", risk: "safe" },
      { pkg: "com.xiaomi.xmsf", desc: "小米推送服务框架", risk: "caution" },
      { pkg: "com.xiaomi.xmsfkeeper", desc: "推送保活", risk: "safe" },
    ]},
    { cat: "HyperOS 广告与分析", items: [
      { pkg: "com.miui.core", desc: "MIUI 核心库", risk: "caution" },
      { pkg: "com.miui.core.internal.services", desc: "MIUI 核心服务", risk: "caution" },
      { pkg: "com.miui.uireporter", desc: "UI 体验上报", risk: "safe" },
      { pkg: "com.miui.rom", desc: "ROM 推广服务", risk: "safe" },
      { pkg: "com.xiaomi.ugd", desc: "用户增长数据", risk: "safe" },
      { pkg: "com.xiaomi.xaee", desc: "异常上报", risk: "safe" },
    ]},
    { cat: "HyperOS Google 服务（国行可精简）", items: [
      { pkg: "com.google.android.gms", desc: "Google 服务框架", risk: "safe" },
      { pkg: "com.google.android.gsf", desc: "Google 服务基础", risk: "safe" },
      { pkg: "com.android.vending", desc: "Google Play 商店", risk: "safe" },
      { pkg: "com.google.android.youtube", desc: "YouTube", risk: "safe" },
      { pkg: "com.google.android.webview", desc: "Android System WebView", risk: "caution" },
    ]},
  ],
  tv: [
    { cat: "系统核心（严禁精简）", items: [
      { pkg: "com.android.settings", desc: "系统设置", risk: "danger" },
      { pkg: "com.mitv.tvhome", desc: "电视桌面", risk: "danger" },
      { pkg: "com.android.systemui", desc: "系统界面", risk: "danger" },
      { pkg: "android", desc: "Android 框架核心", risk: "danger" },
    ]},
    { cat: "电视盒应用", items: [
      { pkg: "com.mipay.wallet.tv", desc: "小米支付(电视)", risk: "caution" },
      { pkg: "com.xiaomi.mibox.gamecenter", desc: "盒子游戏中心", risk: "safe" },
      { pkg: "com.xiaomi.mitv.handbook", desc: "电视使用手册", risk: "safe" },
      { pkg: "com.xiaomi.mitv.pay", desc: "电视支付", risk: "caution" },
      { pkg: "com.xiaomi.mitv.payment", desc: "电视支付服务", risk: "caution" },
      { pkg: "com.xiaomi.mitv.tvpush.tvpushservice", desc: "电视推送服务", risk: "safe" },
    ]},
    { cat: "HyperOS 电视盒应用（澎湃 TV）", items: [
      { pkg: "com.mitv.account", desc: "电视小米账号", risk: "caution" },
      { pkg: "com.mitv.videoplayer", desc: "电视视频播放器", risk: "caution" },
      { pkg: "com.xiaomi.mitv.gallery", desc: "电视相册", risk: "safe" },
      { pkg: "com.xiaomi.mitv.hotspot", desc: "电视热点共享", risk: "safe" },
      { pkg: "com.mitv.hotspot", desc: "电视 Wi-Fi 热点", risk: "safe" },
      { pkg: "com.xiaomi.mitv.globalsetting", desc: "电视全局设置", risk: "caution" },
      { pkg: "com.mitv.globalSetting", desc: "电视全局设置(旧)", risk: "caution" },
      { pkg: "com.xiaomi.mitv.sysservice", desc: "电视系统服务", risk: "caution" },
      { pkg: "com.xiaomi.mitv.upgrade", desc: "电视系统升级", risk: "safe" },
      { pkg: "com.xiaomi.mitv.ovp", desc: "电视在线视频平台", risk: "safe" },
      { pkg: "com.xiaomi.mitv.mivision", desc: "电视视觉/画质引擎", risk: "safe" },
      { pkg: "com.miui.tv.analytics", desc: "电视使用统计", risk: "safe" },
      { pkg: "com.xiaomi.mitv.abtest", desc: "电视 A/B 实验", risk: "safe" },
      { pkg: "com.xiaomi.mitv.mitvsettings", desc: "电视设置增强", risk: "caution" },
      { pkg: "com.xiaomi.mitv.patchwall", desc: "电视壁纸/PatchWall", risk: "safe" },
    ]},
  ],
};

// 暴露为全局，确保 app/index.html 在 file:// 下跨脚本可读取
if (typeof window !== "undefined") {
  window.APP_DATA = APP_DATA;
}
